-- Scene: You're in a cave or tunnel, 
-- looking for resources but not 
-- seeing any within your immediate 
-- vicinity.  So you place your turtle
-- facing a blank wall, fuel it up, put
--  a chest behind it, and launch 
-- "exploreAndMine". The turtle looks 
-- fore, up, down, left and right, but 
-- (assuming this really is a blank 
-- wall) then digs ahead, moves 
-- forward and repeats until it finds 
-- something interesting (iron, 
-- diamond, coal, redstone or 
-- something).  Along the way it makes 
-- a 2-block high tunnel and every 10 
-- blocks it places a torch to its 
-- right. When it finally finds 
-- something it runs Veinminer and 
-- creates a nice rectangular room, 
-- leaves a torch on the floor then 
-- continues forward from there.
-- It continues like this limited by a 
-- maximum block distance from its 
-- starting place, or limited by fuel.